/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.charts;

import business.ImageManager;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GradientPaint;
import java.awt.Point;
import javax.swing.GroupLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.dial.ArcDialFrame;
import org.jfree.chart.plot.dial.DialBackground;
import org.jfree.chart.plot.dial.DialPlot;
import org.jfree.chart.plot.dial.StandardDialRange;
import org.jfree.chart.plot.dial.StandardDialScale;
import org.jfree.chart.ui.GradientPaintTransformType;
import org.jfree.chart.ui.StandardGradientPaintTransformer;
import org.jfree.data.general.DefaultValueDataset;

/**
 *
 * @author jmoura
 */
public final class ChartGauge extends JFrame {

    private static final Log log = LogFactory.getLog(ChartGauge.class);
    private String subtitle;
    private double value;

    public ChartGauge(String title, String subtitle, double value) {
        initComponents();
        configUi(title);
        setsubtitle(subtitle);
        setValue(value);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpQuadro = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 273, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 315, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpQuadroLayout = new javax.swing.GroupLayout(jpQuadro);
        jpQuadro.setLayout(jpQuadroLayout);
        jpQuadroLayout.setHorizontalGroup(
            jpQuadroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpQuadroLayout.setVerticalGroup(
            jpQuadroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpQuadro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpQuadro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jpQuadro.getAccessibleContext().setAccessibleName("BasePanel");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jpQuadro;
    // End of variables declaration//GEN-END:variables

    private void configUi(String title) {
        setTitle(title);
        this.setIconImage(ImageManager.getInstance().getBarChartIcon());
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     *
     * @return A panel.
     */
    private JPanel createPanel() {
        return buildPanel(getSubtitle(), getValue(), 400, 250);
    }

    /**
     * Builds a standalone embeddable gauge panel (a JFreeChart {@link ChartPanel}) with the same DialPlot
     * look as the full window. Used by the Victory Dashboard to lay small gauges side by side without a
     * window storm. The value is clamped to the dial scale (0..100) so the pin never flies off the arc.
     *
     * @param subtitle the caption drawn under the dial
     * @param value    the gauge value (clamped to 0..100)
     * @param width    preferred width in pixels
     * @param height   preferred height in pixels
     * @return the chart panel
     */
    public static ChartPanel buildPanel(String subtitle, double value, int width, int height) {
        return buildPanel(subtitle, value, -1d, -1d, width, height);
    }

    /**
     * Gauge with an optional amber "defeat" band [0, defeatTo] and blue "win" band [winFrom, 100] on the
     * scale, so the needle (your current share) can be read against both thresholds at a glance. Pass a
     * negative / out-of-range bound to omit that band. Value is clamped to 0..100.
     */
    public static ChartPanel buildPanel(String subtitle, double value, double defeatTo, double winFrom, int width, int height) {
        final double clamped = Math.max(0d, Math.min(100d, value));
        JFreeChart chart = createChart(new DefaultValueDataset(clamped), subtitle, defeatTo, winFrom);
        ChartPanel chartPanel = new ChartPanel(chart, false);
        chartPanel.setFillZoomRectangle(true);
        chartPanel.setMouseWheelEnabled(true);
        chartPanel.setPreferredSize(new Dimension(width, height));
        return chartPanel;
    }

    /**
     * Creates the gauge chart.
     *
     * @param dataset  the dataset.
     * @param subtitle the caption drawn under the dial.
     *
     * @return The chart.
     */
    private static JFreeChart createChart(DefaultValueDataset dataset, String subtitle) {
        return createChart(dataset, subtitle, -1d, -1d);
    }

    private static JFreeChart createChart(DefaultValueDataset dataset, String subtitle, double defeatTo, double winFrom) {

        DialPlot dialplot = new DialPlot();
        dialplot.setView(0.20999999999999999D, 0.0D, 0.57999999999999996D, 0.29999999999999999D);
        dialplot.setDataset(dataset);
        ArcDialFrame arcdialframe = new ArcDialFrame(60D, 60D);
        arcdialframe.setInnerRadius(0.59999999999999998D);
        arcdialframe.setOuterRadius(0.90000000000000002D);
        arcdialframe.setForegroundPaint(Color.darkGray);
        arcdialframe.setStroke(new BasicStroke(3F));
        dialplot.setDialFrame(arcdialframe);
        GradientPaint gradientpaint = new GradientPaint(new Point(), new Color(255, 255, 255), new Point(), new Color(240, 240, 240));
        DialBackground dialbackground = new DialBackground(gradientpaint);
        dialbackground.setGradientPaintTransformer(new StandardGradientPaintTransformer(GradientPaintTransformType.VERTICAL));
        dialplot.addLayer(dialbackground);
        StandardDialScale standarddialscale = new StandardDialScale(0.0D, 100D, 115D, -50D, 10D, 4);
        standarddialscale.setTickRadius(0.88D);
        standarddialscale.setTickLabelOffset(0.070000000000000007D);
        standarddialscale.setMajorTickIncrement(25D);
        dialplot.addScale(0, standarddialscale);
        // amber "defeat" band [0, defeatTo] and blue "win" band [winFrom, 100] on the scale.
        if (defeatTo > 0D) {
            StandardDialRange amber = new StandardDialRange(0D, Math.min(100D, defeatTo), new Color(0xE6, 0x51, 0x00));
            amber.setInnerRadius(0.60D);
            amber.setOuterRadius(0.85D);
            dialplot.addLayer(amber);
        }
        if (winFrom >= 0D && winFrom < 100D) {
            StandardDialRange blue = new StandardDialRange(winFrom, 100D, new Color(0x15, 0x65, 0xC0));
            blue.setInnerRadius(0.60D);
            blue.setOuterRadius(0.85D);
            dialplot.addLayer(blue);
        }
        org.jfree.chart.plot.dial.DialPointer.Pin pin = new org.jfree.chart.plot.dial.DialPointer.Pin();
        pin.setRadius(0.81999999999999995D);
        dialplot.addLayer(pin);
        JFreeChart jfreechart = new JFreeChart(dialplot);
        jfreechart.setTitle(subtitle);
        return jfreechart;
    }

    /**
     * set any configs before starting
     */
    final public void doStart() {
        GroupLayout parLayout = (GroupLayout) jpQuadro.getLayout();
        parLayout.replace(jPanel1, createPanel());
    }

    /**
     * @return the subtitle
     */
    public String getSubtitle() {
        return subtitle;
    }

    /**
     * @param title the subtitle to set
     */
    public void setsubtitle(String title) {
        this.subtitle = title;
    }

    /**
     * @return the value
     */
    public double getValue() {
        return value;
    }

    /**
     * @param value the value to set
     */
    public void setValue(double value) {
        this.value = value;
    }
}
