/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.charts;

import business.ImageManager;
import java.awt.BasicStroke;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.RadialGradientPaint;
import java.awt.geom.Ellipse2D;
import java.awt.geom.Point2D;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.GroupLayout;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JPanel;
import persistenceCommons.SettingsManager;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.ChartUtils;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.LineAndShapeRenderer;
import org.jfree.chart.title.TextTitle;
import org.jfree.chart.ui.HorizontalAlignment;
import org.jfree.chart.ui.RectangleEdge;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author jmoura
 */
public class ChartLine extends JFrame {
    
    private static final Log log = LogFactory.getLog(ChartLine.class);
    private final List<DataSetForChart> dataSet;
    private String subtitle = null;
    private String xLabel;
    private String yLabel;
    private PlotOrientation orientation = PlotOrientation.VERTICAL;
    private boolean legendDisplay = true;
    // "% share" mode: plot each series as its share of that turn's total (0-100%) instead of raw values,
    // so relative standing is visible (raw values rise for everyone). Toggled by a checkbox on the window.
    private boolean shareMode = false;
    private JPanel chartHolder;
    
    public ChartLine(String title, List<DataSetForChart> dataSet, String subtitle) {
        initComponents();
        configUi(title);
        this.dataSet = dataSet;
        this.subtitle = subtitle;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpQuadro = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 273, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 315, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpQuadroLayout = new javax.swing.GroupLayout(jpQuadro);
        jpQuadro.setLayout(jpQuadroLayout);
        jpQuadroLayout.setHorizontalGroup(
            jpQuadroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpQuadroLayout.setVerticalGroup(
            jpQuadroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpQuadro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpQuadro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jpQuadro.getAccessibleContext().setAccessibleName("BasePanel");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jpQuadro;
    // End of variables declaration//GEN-END:variables

    private void configUi(String title) {
        setTitle(title);
        this.setIconImage(ImageManager.getInstance().getBarChartIcon());
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     *
     * @return A panel.
     */
    private ChartPanel buildChartPanel() {
        JFreeChart chart = createChart(createDataset());
        ChartPanel chartPanel = new ChartPanel(chart, false);
        chartPanel.setFillZoomRectangle(true);
        chartPanel.setMouseWheelEnabled(true);
        chartPanel.setPreferredSize(new Dimension(500, 270));
        return chartPanel;
    }

    /** Rebuild the chart in place after the %-share toggle flips. */
    private void refreshChart() {
        if (chartHolder == null) {
            return;
        }
        chartHolder.removeAll();
        chartHolder.add(buildChartPanel(), BorderLayout.CENTER);
        chartHolder.revalidate();
        chartHolder.repaint();
    }

    private String tx(String key, String fallback) {
        final String s = SettingsManager.getInstance().getBundleManager().getString(key);
        return (s == null || s.startsWith("N/A (Missing Translation")) ? fallback : s;
    }

    /**
     * Returns a sample dataset.
     *
     * @return The dataset.
     */
    private CategoryDataset createDataset() {
        DefaultCategoryDataset chartDataset = new DefaultCategoryDataset();
        if (shareMode) {
            // per-category (turn) totals, then emit each value as its % of that turn's total
            final Map<String, Double> totals = new HashMap<>();
            for (DataSetForChart item : dataSet) {
                totals.merge(item.getGrouping(), item.getValue(), Double::sum);
            }
            for (DataSetForChart item : dataSet) {
                final double total = totals.getOrDefault(item.getGrouping(), 0.0);
                final double pct = total > 0 ? item.getValue() / total * 100.0 : 0.0;
                chartDataset.addValue(pct, item.getKey(), item.getGrouping());
            }
        } else {
            for (DataSetForChart item : dataSet) {
                //value; series; x-axis (i.e. turns)
                chartDataset.addValue(item.getValue(), item.getKey(), item.getGrouping());
            }
        }
        return chartDataset;
        /*
        dataset.addValue(212, "Classes", "JDK 1.0");
        dataset.addValue(504, "Classes", "JDK 1.1");
        dataset.addValue(1520, "Classes", "JDK 1.2");
        dataset.addValue(1842, "Classes", "JDK 1.3");
        dataset.addValue(2991, "Classes", "JDK 1.4");
        dataset.addValue(3500, "Classes", "JDK 1.5");

         */
    }

    /**
     * Creates a sample chart.
     *
     * @param dataset the dataset.
     *
     * @return The chart.
     */
    private JFreeChart createChart(CategoryDataset dataset) {
        final String yAxisLabel = shareMode ? tx("CHART.LINE.SHARE.AXIS", "% share") : this.getyLabel();
        JFreeChart chart = ChartFactory.createLineChart(
                getTitle(),
                this.getxLabel(), yAxisLabel,
                dataset,
                this.getOrientation(),// Plot orientation 
                this.isLegendDisplay(), // include legend
                true, // include tooltips
                false // include URLs
        );
        if (subtitle != null) {
            TextTitle source = new TextTitle(this.subtitle);
            source.setFont(new Font("SansSerif", Font.PLAIN, 10));
            source.setPosition(RectangleEdge.BOTTOM);
            source.setHorizontalAlignment(HorizontalAlignment.RIGHT);
            chart.addSubtitle(source);
        }
        chart.setBackgroundPaint(Color.WHITE);
        CategoryPlot plot = (CategoryPlot) chart.getPlot();
        plot.setRangePannable(true);
        plot.setRangeGridlinesVisible(false);
        // Turns are many -> angle the x-axis (turn) labels so they don't collapse to "..." at full width.
        plot.getDomainAxis().setCategoryLabelPositions(org.jfree.chart.axis.CategoryLabelPositions.UP_45);
        // customise the range axis...
        NumberAxis rangeAxis = (NumberAxis) plot.getRangeAxis();
        rangeAxis.setStandardTickUnits(NumberAxis.createIntegerTickUnits());
        
        ChartUtils.applyCurrentTheme(chart);

        // customise the renderer... (apply AFTER the theme so our per-series styling wins)
        LineAndShapeRenderer renderer = (LineAndShapeRenderer) plot.getRenderer();
        renderer.setDefaultLinesVisible(true);
        renderer.setDefaultShapesVisible(false);
        // Per-nation styling: colour = nation identity; stroke = allegiance (solid = your side, dashed =
        // enemy); your own nation is emphasised (thicker + round markers). Style comes from the first
        // data point seen for each series (all points of a nation share it).
        final java.util.Map<String, DataSetForChart> styleByKey = new java.util.LinkedHashMap<>();
        for (DataSetForChart d : dataSet) {
            styleByKey.putIfAbsent(d.getKey(), d);
        }
        for (int i = 0; i < dataset.getRowCount(); i++) {
            final DataSetForChart s = styleByKey.get((String) dataset.getRowKey(i));
            if (s == null) {
                continue;
            }
            renderer.setSeriesPaint(i, s.getColor());
            final float w = s.isEmphasis() ? 3.5f : 2.0f;
            if (s.isDashed()) {
                renderer.setSeriesStroke(i, new BasicStroke(w, BasicStroke.CAP_ROUND, BasicStroke.JOIN_ROUND,
                        1.0f, new float[]{6.0f, 6.0f}, 0.0f));
            } else {
                renderer.setSeriesStroke(i, new BasicStroke(w, BasicStroke.CAP_ROUND, BasicStroke.JOIN_ROUND));
            }
            renderer.setSeriesShapesVisible(i, s.isEmphasis());
            if (s.isEmphasis()) {
                renderer.setSeriesShape(i, new Ellipse2D.Double(-3.0, -3.0, 6.0, 6.0));
            }
        }
        return chart;
    }

    /**
     * A utility method for creating gradient paints.
     *
     * @param c1 color 1.
     * @param c2 color 2.
     *
     * @return A radial gradient paint.
     */
    private RadialGradientPaint createGradientPaint(Color c1, Color c2) {
        Point2D center = new Point2D.Float(0, 0);
        float radius = 200;
        float[] dist = {0.0f, 1.0f};
        return new RadialGradientPaint(center, radius, dist, new Color[]{c1, c2});
    }

    /**
     * set any configs before starting
     */
    final public void doStart() {
        final JPanel container = new JPanel(new BorderLayout());
        final JPanel top = new JPanel(new FlowLayout(FlowLayout.LEFT, 6, 2));
        final JCheckBox shareToggle = new JCheckBox(tx("CHART.LINE.SHARE", "Show % share"));
        shareToggle.setToolTipText(tx("CHART.LINE.SHARE.TOOLTIP",
                "Plot each nation's share of the total this turn, instead of raw points."));
        shareToggle.addActionListener(e -> {
            shareMode = shareToggle.isSelected();
            refreshChart();
        });
        top.add(shareToggle);
        container.add(top, BorderLayout.NORTH);
        chartHolder = new JPanel(new BorderLayout());
        chartHolder.add(buildChartPanel(), BorderLayout.CENTER);
        container.add(chartHolder, BorderLayout.CENTER);
        GroupLayout parLayout = (GroupLayout) jpQuadro.getLayout();
        parLayout.replace(jPanel1, container);
    }

    /**
     * @return the xLabel
     */
    public String getxLabel() {
        return xLabel;
    }

    /**
     * @param xLabel the xLabel to set
     */
    public void setxLabel(String xLabel) {
        this.xLabel = xLabel;
    }

    /**
     * @return the yLabel
     */
    public String getyLabel() {
        return yLabel;
    }

    /**
     * @param yLabel the yLabel to set
     */
    public void setyLabel(String yLabel) {
        this.yLabel = yLabel;
    }

    /**
     * @return the orientation
     */
    public PlotOrientation getOrientation() {
        return orientation;
    }

    /**
     * @param orientation the orientation to set
     */
    public void setOrientation(PlotOrientation orientation) {
        this.orientation = orientation;
    }
    
    public void setOrientation(boolean vertical) {
        if (vertical) {
            this.orientation = PlotOrientation.VERTICAL;
        } else {
            this.orientation = PlotOrientation.HORIZONTAL;
        }
    }

    /**
     * @return the legendDisplay
     */
    public boolean isLegendDisplay() {
        return legendDisplay;
    }

    /**
     * @param legendDisplay the legendDisplay to set
     */
    public void setLegendDisplay(boolean legendDisplay) {
        this.legendDisplay = legendDisplay;
    }
}
