/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * MainAboutBox.java
 *
 * Created on 21/Abr/2011, 7:42:51
 */
package gui.accessories;

import business.ImageManager;
import gui.TabBase;
import gui.components.ButtonLink;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.Serializable;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import persistenceCommons.BundleManager;
import persistenceCommons.SettingsManager;
import persistenceCommons.SysApoio;

/**
 *
 * @author jmoura
 */
public class MainAboutBox extends TabBase implements Serializable {

    private static final Log log = LogFactory.getLog(MainAboutBox.class);
    private static final BundleManager labels = SettingsManager.getInstance().getBundleManager();

    /**
     * Creates new form MainAboutBox
     */
    public MainAboutBox() {
        initComponents();
        config();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lAboutTitle = new javax.swing.JLabel();
        lWebadminTitle = new javax.swing.JLabel();
        lWebsiteLink = new javax.swing.JLabel();
        lMaillistTitle = new javax.swing.JLabel();
        lMaillistLink = new javax.swing.JLabel();
        lModeratorTitle = new javax.swing.JLabel();
        lModeratorLink = new javax.swing.JLabel();
        lCommonsTitle = new javax.swing.JLabel();
        lCommons = new javax.swing.JLabel();
        lCounselorTitle = new javax.swing.JLabel();
        lClient = new javax.swing.JLabel();
        lFacebookTitle = new javax.swing.JLabel();
        lFacebookLink = new javax.swing.JLabel();
        lWebsiteTitle = new javax.swing.JLabel();
        lWebAdminLink = new javax.swing.JLabel();
        lJavaTitle = new javax.swing.JLabel();
        lJava = new javax.swing.JLabel();
        lScreenTitle = new javax.swing.JLabel();
        lScreen = new javax.swing.JLabel();
        lOsTitle = new javax.swing.JLabel();
        lOs = new javax.swing.JLabel();
        lIconLabel = new javax.swing.JLabel();
        lFacebookTitle1 = new javax.swing.JLabel();
        lModeratorTitle1 = new javax.swing.JLabel();
        lModeratorLink1 = new javax.swing.JLabel();
        lFacebookLink1 = new javax.swing.JLabel();
        lNewVersion = new javax.swing.JLabel();

        lAboutTitle.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lAboutTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lAboutTitle.setText(labels.getString("ABOUT.TITLE")); // NOI18N

        lWebadminTitle.setText("Site do Jogo");

        lWebsiteLink.setText("http://sites.google.com/site/clashlegends");

        lMaillistTitle.setText("Grupo de Discussão");

        lMaillistLink.setText("http://groups.google.com/group/clashoflegends");

        lModeratorTitle.setText("Moderator's email");

        lModeratorLink.setText("ClashOfLegends.theGame@gmail.com");

        lCommonsTitle.setText(labels.getString("ABOUT.COMMONS")); // NOI18N

        lCommons.setText("1.999");

        lCounselorTitle.setText(labels.getString("ABOUT.CLIENT")); // NOI18N

        lClient.setText("1.999");

        lFacebookTitle.setText("Facebook");

        lFacebookLink.setText("http://www.facebook.com/ClashOfLegends");

        lWebsiteTitle.setText("Site do Jogo");

        lWebAdminLink.setText("http://sites.google.com/site/clashlegends");

        lJavaTitle.setText(labels.getString("ABOUT.JAVA.VERSION")); // NOI18N

        lJava.setText("1.999");

        lScreenTitle.setText(labels.getString("ABOUT.SCREEN.RESOLUTION")); // NOI18N

        lScreen.setText("1.999");

        lOsTitle.setText(labels.getString("ABOUT.OS.VERSION")); // NOI18N

        lOs.setText("1.999");

        lIconLabel.setText("iconLabel");
        lIconLabel.setMaximumSize(new java.awt.Dimension(48, 48));
        lIconLabel.setMinimumSize(new java.awt.Dimension(48, 48));
        lIconLabel.setPreferredSize(new java.awt.Dimension(48, 48));

        lFacebookTitle1.setText("Facebook");

        lModeratorTitle1.setText("Moderator's email");

        lModeratorLink1.setText("ClashOfLegends.theGame@gmail.com");

        lFacebookLink1.setText("http://www.facebook.com/ClashOfLegends");

        lNewVersion.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lAboutTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lCounselorTitle)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lNewVersion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(lCommonsTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lJavaTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lScreenTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lOsTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lCommons)
                                    .addComponent(lClient)
                                    .addComponent(lJava)
                                    .addComponent(lScreen)
                                    .addComponent(lOs)))
                            .addComponent(lFacebookLink1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lModeratorLink1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lFacebookLink, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lModeratorLink, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lMaillistLink, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                            .addComponent(lWebsiteLink, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lWebAdminLink, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lFacebookTitle1)
                            .addComponent(lModeratorTitle1)
                            .addComponent(lFacebookTitle)
                            .addComponent(lWebadminTitle)
                            .addComponent(lMaillistTitle)
                            .addComponent(lModeratorTitle)
                            .addComponent(lWebsiteTitle))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(lIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lAboutTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lWebadminTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lWebAdminLink)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lWebsiteTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lWebsiteLink)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lMaillistTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lMaillistLink)
                .addGap(18, 18, 18)
                .addComponent(lModeratorTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lModeratorLink)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lFacebookTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lFacebookLink)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lModeratorTitle1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lModeratorLink1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lFacebookTitle1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lFacebookLink1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCounselorTitle)
                    .addComponent(lClient)
                    .addComponent(lNewVersion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCommonsTitle)
                    .addComponent(lCommons))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lJava)
                    .addComponent(lJavaTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lScreen)
                    .addComponent(lScreenTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lOs)
                    .addComponent(lOsTitle))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lAboutTitle;
    private javax.swing.JLabel lClient;
    private javax.swing.JLabel lCommons;
    private javax.swing.JLabel lCommonsTitle;
    private javax.swing.JLabel lCounselorTitle;
    private javax.swing.JLabel lFacebookLink;
    private javax.swing.JLabel lFacebookLink1;
    private javax.swing.JLabel lFacebookTitle;
    private javax.swing.JLabel lFacebookTitle1;
    private javax.swing.JLabel lIconLabel;
    private javax.swing.JLabel lJava;
    private javax.swing.JLabel lJavaTitle;
    private javax.swing.JLabel lMaillistLink;
    private javax.swing.JLabel lMaillistTitle;
    private javax.swing.JLabel lModeratorLink;
    private javax.swing.JLabel lModeratorLink1;
    private javax.swing.JLabel lModeratorTitle;
    private javax.swing.JLabel lModeratorTitle1;
    private javax.swing.JLabel lNewVersion;
    private javax.swing.JLabel lOs;
    private javax.swing.JLabel lOsTitle;
    private javax.swing.JLabel lScreen;
    private javax.swing.JLabel lScreenTitle;
    private javax.swing.JLabel lWebAdminLink;
    private javax.swing.JLabel lWebadminTitle;
    private javax.swing.JLabel lWebsiteLink;
    private javax.swing.JLabel lWebsiteTitle;
    // End of variables declaration//GEN-END:variables

    private void config() {
        log.info(System.getProperties().toString());
        lClient.setText("2." + SysApoio.getVersionClash("version_counselor"));
        lCommons.setText("1." + SysApoio.getVersionClash("version_commons"));
        lJava.setText(SysApoio.getVersionJava());
        lOs.setText(SysApoio.getVersionOs());
        lScreen.setText(SysApoio.getScreenSize());
        lAboutTitle.setText(labels.getString("ABOUT.TITLE"));
        lWebsiteTitle.setText(labels.getString("ABOUT.WEB.TITLE"));
        lWebadminTitle.setText(labels.getString("ABOUT.WEBADMIN.TITLE"));
        lMaillistTitle.setText(labels.getString("ABOUT.MAIL.TITLE"));
        lCounselorTitle.setText(labels.getString("ABOUT.CLIENT"));
        lCommonsTitle.setText(labels.getString("ABOUT.COMMONS"));
        lModeratorTitle.setText(labels.getString("ABOUT.MODERATOR.TITLE"));
        lFacebookTitle.setText(labels.getString("ABOUT.FACEBOOK.TITLE"));

        lNewVersion.setVisible(false); // shown only if the update check found a newer version (below)
        try {
            GroupLayout parLayout = (GroupLayout) jPanel1.getLayout();
            ButtonLink webAdmin = new ButtonLink(labels.getString("ABOUT.WEBADMIN.LINK"), labels.getString("ABOUT.WEBADMIN.LINK"));
            parLayout.replace(lWebAdminLink, webAdmin);
            ButtonLink webLink = new ButtonLink(labels.getString("ABOUT.WEB.LINK"), labels.getString("ABOUT.WEB.LINK"));
            parLayout.replace(lWebsiteLink, webLink);
            ButtonLink mailLink = new ButtonLink(labels.getString("ABOUT.MAIL.LINK"), labels.getString("ABOUT.MAIL.LINK"));
            parLayout.replace(lMaillistLink, mailLink);
            ButtonLink moderatorLink = new ButtonLink(labels.getString("ABOUT.MODERATOR.LINK"), "mailto:" + labels.getString("ABOUT.MODERATOR.LINK"));
            parLayout.replace(lModeratorLink, moderatorLink);
            ButtonLink facebookLink = new ButtonLink(labels.getString("ABOUT.FACEBOOK.LINK"), labels.getString("ABOUT.FACEBOOK.LINK"));
            parLayout.replace(lFacebookLink, facebookLink);

            // New-version indicator: clickable "download" link to the latest release, shown only when
            // the update check found a newer version; the placeholder stays hidden otherwise.
            final String newVer = control.services.UpdateChecker.getAvailableVersion();
            if (newVer != null) {
                ButtonLink update = new ButtonLink(
                        String.format(labels.getString("ABOUT.UPDATE.LINK"), newVer),
                        control.services.UpdateChecker.getLatestReleaseUrl());
                update.setIcon(updateIcon());
                parLayout.replace(lNewVersion, update);
            }

            // Icon above title
            Image img = ImageManager.getInstance().getIconApp();
            if (img != null) {
                parLayout.replace(lIconLabel, new JLabel(new ImageIcon(img.getScaledInstance(48, 48, Image.SCALE_SMOOTH))));
            }
        } catch (Exception e) {
            lMaillistLink.setText(labels.getString("ABOUT.MAIL.LINK"));
            lWebAdminLink.setText(labels.getString("ABOUT.WEBADMIN.LINK"));
            lWebsiteLink.setText(labels.getString("ABOUT.WEB.LINK"));
            lModeratorLink.setText(labels.getString("ABOUT.MODERATOR.LINK"));
        }

        // Path rows — appended below jPanel1 via BorderLayout
        String dataDir = SysApoio.getInstallerDataDir();
        if (dataDir == null) {
            dataDir = new File("").getAbsolutePath();
        }
        final String configPath = dataDir + File.separator + "properties.config";
        final String logDirPath = dataDir;

        JPanel pathPanel = new JPanel();
        pathPanel.setLayout(new BoxLayout(pathPanel, BoxLayout.Y_AXIS));
        pathPanel.setBorder(BorderFactory.createEmptyBorder(2, 10, 8, 10));
        pathPanel.add(makePathRow("Config file:", configPath, new File(configPath), false));
        pathPanel.add(Box.createVerticalStrut(4));
        pathPanel.add(makePathRow("Logs folder:", logDirPath, new File(logDirPath), true));

        this.setLayout(new BorderLayout());
        this.add(jPanel1, BorderLayout.CENTER);
        this.add(pathPanel, BorderLayout.SOUTH);
    }

    /** Theme-aware "download" icon for the new-version link (bundled Tabler SVG). */
    private static javax.swing.Icon updateIcon() {
        com.formdev.flatlaf.extras.FlatSVGIcon icon = new com.formdev.flatlaf.extras.FlatSVGIcon("images/icons/download.svg", 16, 16);
        icon.setColorFilter(new com.formdev.flatlaf.extras.FlatSVGIcon.ColorFilter(
                c -> javax.swing.UIManager.getColor("Label.foreground")));
        return icon;
    }

    private JPanel makePathRow(String labelText, String pathText, File target, boolean openDir) {
        JPanel row = new JPanel();
        row.setLayout(new BoxLayout(row, BoxLayout.X_AXIS));
        row.setAlignmentX(Component.LEFT_ALIGNMENT);
        row.setOpaque(false);
        JLabel label = new JLabel(labelText);
        label.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 8));
        row.add(label);
        JLabel link = new JLabel("<html><a href=''>" + pathText + "</a></html>");
        link.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        link.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                try {
                    if (openDir || !target.exists()) {
                        File dir = openDir ? target : target.getParentFile();
                        Desktop.getDesktop().open(dir);
                    } else {
                        Desktop.getDesktop().open(target);
                    }
                } catch (Exception ex) {
                    log.warn("Cannot open: " + target);
                }
            }
        });
        row.add(link);
        return row;
    }
}
