/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * SubTabTextArea.java
 *
 * Created on 17/Abr/2011, 9:35:23
 */
package gui.subtabs;

import control.OrdemControlerFloater;
import control.support.DispatchManager;
import gui.TabBase;
import gui.services.IDispatchReceiver;
import gui.services.IPopupTabGui;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.io.Serializable;
import javax.swing.GroupLayout;
import javax.swing.JDialog;
import javax.swing.JFrame;
import model.Local;
import model.Nacao;
import model.PersonagemOrdem;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import persistenceCommons.BundleManager;
import persistenceCommons.SettingsManager;

/**
 *
 * @author jmoura
 */
public class SubTabPopup extends TabBase implements IPopupTabGui, IDispatchReceiver, Serializable {

    private static final Log log = LogFactory.getLog(SubTabPopup.class);
    private static final BundleManager labels = SettingsManager.getInstance().getBundleManager();
    private final JDialog dPopup = new JDialog(new JFrame(), false);
    private final SubTabTextArea stContent = new SubTabTextArea();
    private String guiConfig = "";

    /**
     * Creates new form SubTabTextArea
     */
    public SubTabPopup() {
        initComponents();
        iniciaConfig();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbDetach = new javax.swing.JToggleButton();
        jMaster = new javax.swing.JScrollPane();

        jbDetach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/detach.png"))); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("labels"); // NOI18N
        jbDetach.setToolTipText(bundle.getString("PERSONAGEM.DETACH.TOOLTIP")); // NOI18N
        jbDetach.setFocusable(false);
        jbDetach.setMaximumSize(new java.awt.Dimension(23, 23));
        jbDetach.setMinimumSize(new java.awt.Dimension(23, 23));
        jbDetach.setPreferredSize(new java.awt.Dimension(23, 23));

        jMaster.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 392, Short.MAX_VALUE)
                .addComponent(jbDetach, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jMaster)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jbDetach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jMaster, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jMaster;
    private javax.swing.JToggleButton jbDetach;
    // End of variables declaration//GEN-END:variables

    private void iniciaConfig() {
        //monta a floating window para ordens
        final OrdemControlerFloater ordemControlFloater = new OrdemControlerFloater(this);
        dPopup.setTitle(labels.getString("INFORMATION.TITLE"));
        dPopup.setAlwaysOnTop(true);
        dPopup.addComponentListener(ordemControlFloater);
        dPopup.setName("dPopup");
        jbDetach.setActionCommand("jbDetach");
        jbDetach.addItemListener(ordemControlFloater);
        jMaster.setViewportView(stContent);
        DispatchManager.getInstance().registerForMsg(DispatchManager.WINDOWS_CLOSING, this);
    }

    public void setText(String title, String text) {
        dPopup.setTitle(title);
        stContent.setText(text);
    }

    public void setTextBackground(Color color) {
        this.stContent.setBackground(color);
    }

    public void setFontMonospaced() {
        this.stContent.setFontMonospaced();
    }

    public void setFontText(Font f) {
        this.stContent.setFont(f);
    }

    public void replace(Component oldComponent) {
        GroupLayout parLayout = (GroupLayout) oldComponent.getParent().getLayout();
        parLayout.replace(oldComponent, this);
    }

    @Override
    public void doDetachTogglePopup() {
        //change triggered by CheckBox
        if (jbDetach.isSelected()) {
            doDetachPopup();
        } else {
            doAttachPopup();
        }
    }

    @Override
    public void doDetachPopup() {
        //monta a floating window para ordens
        dPopup.add(stContent);
        //load configs
        int width = SettingsManager.getInstance().getConfigAsInt(getGuiConfig() + "SizeWidth", "500");
        int height = SettingsManager.getInstance().getConfigAsInt(getGuiConfig() + "SizeHeight", "400");
        int posX = SettingsManager.getInstance().getConfigAsInt(getGuiConfig() + "PositionX", "1");
        int posY = SettingsManager.getInstance().getConfigAsInt(getGuiConfig() + "PositionY", "1");
        //configura jDialog
        if (!SettingsManager.getInstance().isKeyExist(getGuiConfig() + "PositionY")) {
            dPopup.setLocationRelativeTo(jMaster);
        } else {
            dPopup.setLocation(posX, posY);
        }
        dPopup.setPreferredSize(new Dimension(width, height));
        dPopup.pack();
        dPopup.setVisible(true);
        jMaster.repaint();
        SettingsManager.getInstance().setConfigAndSaveToFile(getGuiConfigDetachedStatus(), IPopupTabGui.POPUP_FLOATING);
    }

    @Override
    public void doAttachPopup() {
        //closing dialog, forced to redraw and detach
        dPopup.setVisible(false);
        jbDetach.setSelected(false);
        jMaster.setViewportView(stContent);
        SettingsManager.getInstance().setConfigAndSaveToFile(getGuiConfigDetachedStatus(), IPopupTabGui.POPUP_DOCKED);
    }

    public void setGuiConfig(String guiConfig) {
        this.guiConfig = guiConfig;
    }

    @Override
    public String getGuiConfig() {
        return this.guiConfig;
    }

    @Override
    public String getGuiConfigDetachedStatus() {
        return this.guiConfig + "DetachedStatus";
    }

    @Override
    public void receiveDispatch(int msgName) {
        //save windows config
        //log.info(String.format("SubTabPopup: %s; size (%s); coord: (%s);", getGuiConfig(), dPopup.getSize().toString(), dPopup.getLocation().toString()));
        if (dPopup.getSize().width == 0) {
            //do not save if window does not exist
            return;
        }
        SettingsManager.getInstance().setConfig(getGuiConfig() + "SizeWidth", dPopup.getSize().width + "");
        SettingsManager.getInstance().setConfig(getGuiConfig() + "SizeHeight", dPopup.getSize().height + "");
        SettingsManager.getInstance().setConfig(getGuiConfig() + "PositionX", dPopup.getLocation().x + "");
        SettingsManager.getInstance().setConfigAndSaveToFile(getGuiConfig() + "PositionY", dPopup.getLocation().y + "");
    }

    @Override
    public void receiveDispatch(int msgName, String txt) {
    }

    @Override
    public void receiveDispatch(int msgName, Local local) {
    }

    @Override
    public void receiveDispatch(int msgName, Local local, int range) {
    }

    @Override
    public void receiveDispatch(int msgName, Component cmpnt) {
    }

    @Override
    public void receiveDispatch(Nacao nation, PersonagemOrdem before, PersonagemOrdem after) {
    }
}
